env: "dev"
grpc_server:
  address: "localhost:8095"
http_server:
  address: "localhost:8096"
db:
  ip_address: "localhost"
  port: 5432
  user: "postgres"
  password: "root"
  db_name: "marketplace-payment"