// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/payments": {
            "post": {
                "security": [
                    {
                        "AccountId": []
                    },
                    {
                        "AccountType": []
                    }
                ],
                "description": "Подтверждение оплата заказа покупателя",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "payments"
                ],
                "summary": "Подтверждение оплаты заказа",
                "operationId": "confirm-payment",
                "parameters": [
                    {
                        "description": "Платёж",
                        "name": "payment",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_Reswero_Marketplace-v1_payment_internal_delivery_http_payments.PaymentVm"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/responses.StatusResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/responses.StatusResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "github_com_Reswero_Marketplace-v1_payment_internal_delivery_http_payments.PaymentVm": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                }
            }
        },
        "responses.StatusResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "status": {
                    "type": "integer"
                }
            }
        }
    },
    "securityDefinitions": {
        "AccountId": {
            "type": "apiKey",
            "name": "X-Account-Id",
            "in": "header"
        },
        "AccountType": {
            "type": "apiKey",
            "name": "X-Account-Type",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8096",
	BasePath:         "/v1",
	Schemes:          []string{},
	Title:            "Payment Service",
	Description:      "Сервис оплаты заказов",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
