env: "dev"
cache:
  address: "localhost:6379"
http_server:
  address: "localhost:8089"
products:
  address: "http://localhost:8087"
  timeout_ms: 500
orders:
  address: "http://localhost:8090"
  timeout_ms: 500