env: "dev"
db:
  ip_address: "localhost"
  port: 5432
  user: "postgres"
  password: "root"
  db_name: "marketplace-favorites"
cache:
  address: "localhost:6379"
http_server:
  address: "localhost:8088"
products:
  address: "http://localhost:8087"
  timeout_ms: 500